apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: api
      containers:
        - name: api
          image: northamerica-northeast1-docker.pkg.dev/phx-01j1tbke0ax/phx-01j1tbke0ax-safeinputs/api:main-4775b1c-1731446148 # {"$imagepolicy": "flux-system:api"}
          securityContext:
            # No new privs for process or it's children
            # https://github.com/kubernetes/design-proposals-archive/blob/main/auth/no-new-privs.md
            allowPrivilegeEscalation: false
          env:
            - name: MDB_CONNECT_STRING
              valueFrom:
                secretKeyRef:
                  name: mongodb-api-user-connect-string
                  key: connectionString.standardSrv
            - name: MIDDLEWARE_COOKIE_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: middleware_cookie_signing_secret
            - name: MIDDLEWARE_SESSION_STORE_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: middleware_session_store_secret
            - name: MIDDLEWARE_CSRF_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: middleware_csrf_secret
            - name: AUTHN_MAGIC_LINK_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: authn_magic_link_secret
            - name: AUTHN_GC_NOTIFY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: authn_gc_notify_api_key
            - name: AUTHN_GC_NOTIFY_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: authn_gc_notify_template_id
            - name: AUTHZ_EMAIL_HOSTS_ALLOWED
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: authz_email_hosts_allowed
            - name: AUTHZ_EMAIL_HOSTS_ALLOWED_TO_OWN_COLLECTIONS
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: authz_email_hosts_allowed_to_own_collections
            - name: AUTHZ_SUPER_ADMINS
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: authz_super_admins
          resources:
            requests:
              cpu: 200m
              memory: 400Mi
status: {}
