creation_rules:
  # for all yaml files, encrypt data / stringData fields using GCP KMS
  - path_regex: .*.yaml
    encrypted_regex: '^(data|stringData)$'
    gcp_kms: projects/phx-01j1tbke0ax/locations/northamerica-northeast1/keyRings/phx-01j1tbke0ax-sops/cryptoKeys/phx-01j1tbke0ax-sops-flux-key
