steps:
  - id: 'Install dependencies'
    name: 'node:lts-alpine3.19@sha256:94f0e02505b6e29bcdf363e512b35dd0bfb759ed04b2bb401874d0a95b16c4e9'
    entrypoint: 'npm'
    dir: ./
    args: ['ci'] # assumes postinstall script in the root level package.json to also install the sub-directory dependencies

  - id: 'Prettier check'
    name: 'node:lts-alpine3.19@sha256:94f0e02505b6e29bcdf363e512b35dd0bfb759ed04b2bb401874d0a95b16c4e9'
    entrypoint: 'npm'
    dir: ./
    args: ['run', 'prettier']

  - id: 'Eslint check'
    name: 'node:lts-alpine3.19@sha256:94f0e02505b6e29bcdf363e512b35dd0bfb759ed04b2bb401874d0a95b16c4e9'
    entrypoint: 'npm'
    dir: ./
    args: ['run', 'eslint:ci'] # currently allowing warnings, but could be tightened up post https://github.com/PHACDataHub/safe-inputs/issues/144
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
