steps:
  - id: 'Install dependencies'
    name: 'node:lts-alpine3.19@sha256:2ef8a5348c8936329810271059b2c1ba88f293f4d6849e5d2ade22652c3d396c'
    entrypoint: 'npm'
    dir: ./
    args: ['run', 'ci:all'] # script in the root package.json which runs ci at the root and in each sub-project

  - id: 'Prettier check'
    name: 'node:lts-alpine3.19@sha256:2ef8a5348c8936329810271059b2c1ba88f293f4d6849e5d2ade22652c3d396c'
    entrypoint: 'npm'
    dir: ./
    args: ['run', 'prettier']

  - id: 'Eslint check'
    name: 'node:lts-alpine3.19@sha256:2ef8a5348c8936329810271059b2c1ba88f293f4d6849e5d2ade22652c3d396c'
    entrypoint: 'npm'
    dir: ./
    args: ['run', 'eslint:ci'] # currently allowing warnings, but could be tightened up post https://github.com/PHACDataHub/safe-inputs/issues/144

  - id: 'GraphQL Codegen check'
    name: 'gcr.io/cloud-builders/docker@sha256:505f7f83b55bfd222e0554f89aa09ee46e17245b5e376dd430b40b621b41757a'
    dir: ./
    script: |
      #!/bin/bash
      set -o errexit
      set -o pipefail
      set -o nounset

      # docker compose dev environment, detached mode, with the unnecessary services disabled (would disable the ui service too, but the gateway service needs it)
      docker compose -f ./docker-compose.dev.yaml up --detach --scale seed-dev-data=0 --scale ui-gql-codegen=0

      # running the codegen check from a separate container, outside of the docker compose environment, because when I was using the codegen
      # check inside the compose environment (with the --exit-code-from flag set), cloud build was consistently getting 137 exit codes
      # regardless of the outcome of the checks. See: https://github.com/HC-IPPM/safe-inputs/pull/724/commits/36abe66a15020daf70f3ed3e4d3dbd5b3b96fd0b
      docker run \
        --volume "${PWD}":/home/project \
        --workdir /home/project \
        --network host \
        --entrypoint npm \
        node:lts-alpine3.19@sha256:2d8c24d9104bda27e07dced6d7110aa728dd917dde8255d8af3678e532b339d6 \
        run gql-codegen:check

      docker compose -f ./docker-compose.dev.yaml down

  - id: generate-sbom-if-main
    name: 'gcr.io/cloud-builders/docker@sha256:505f7f83b55bfd222e0554f89aa09ee46e17245b5e376dd430b40b621b41757a'
    dir: ui
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo $BRANCH_NAME
        if [[ "$BRANCH_NAME" == "main" ]]
        then
          docker run --rm -v /workspace:/workspace anchore/syft:latest /workspace -o cyclonedx-json > /workspace/sbom.json
        else
          exit 0
        fi

  - id: upload-sbom-to-gcs-bucket-if-main
    name: 'gcr.io/cloud-builders/gsutil@sha256:73670c2b572ada3e8bb8b432f5b965c5b67424000aced53c2f5a28557aca97b8'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "main" ]]
        then
          gsutil cp /workspace/sbom.json gs://safe-inputs-devsecops-outputs-for-dashboard/SBOM/SBOM-${COMMIT_SHA}.json
        else
          exit 0
        fi

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
