steps:
  - id: 'Install dependencies'
    name: 'node:lts-alpine3.19@sha256:97f02cbb1c8ef6eefcfb1b1f958c012362758972cf125a99c09bd18b26a716c9'
    entrypoint: 'npm'
    dir: ./
    args: ['ci'] # assumes postinstall script in the root level package.json to also install the sub-directory dependencies

  - id: 'Prettier check'
    name: 'node:lts-alpine3.19@sha256:97f02cbb1c8ef6eefcfb1b1f958c012362758972cf125a99c09bd18b26a716c9'
    entrypoint: 'npm'
    dir: ./
    args: ['run', 'prettier']

  - id: 'Eslint check'
    name: 'node:lts-alpine3.19@sha256:97f02cbb1c8ef6eefcfb1b1f958c012362758972cf125a99c09bd18b26a716c9'
    entrypoint: 'npm'
    dir: ./
    args: ['run', 'eslint:ci'] # currently allowing warnings, but could be tightened up post https://github.com/PHACDataHub/safe-inputs/issues/144
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
