steps:
  - id: 'Install dependencies'
    name: 'node:22-alpine3.21@sha256:f2dc6eea95f787e25f173ba9904c9d0647ab2506178c7b5b7c5a3d02bc4af145'
    entrypoint: 'npm'
    dir: ./
    args: ['run', 'ci:all'] # script in the root package.json which runs ci at the root and in each sub-project

  - id: 'Prettier check'
    name: 'node:22-alpine3.21@sha256:f2dc6eea95f787e25f173ba9904c9d0647ab2506178c7b5b7c5a3d02bc4af145'
    entrypoint: 'npm'
    dir: ./
    args: ['run', 'prettier']

  - id: 'Eslint check'
    name: 'node:22-alpine3.21@sha256:f2dc6eea95f787e25f173ba9904c9d0647ab2506178c7b5b7c5a3d02bc4af145'
    entrypoint: 'npm'
    dir: ./
    args: ['run', 'eslint:ci'] # currently allowing warnings, but could be tightened up post https://github.com/PHACDataHub/safe-inputs/issues/144

  - id: 'GraphQL Codegen check'
    name: 'gcr.io/cloud-builders/docker@sha256:b991d50960b337f581ad77ea2a59259a786d177019aa64d8b3acb01f65dbc154'
    dir: ./
    script: |
      #!/bin/bash
      set -o errexit
      set -o pipefail
      set -o nounset

      # docker compose dev environment, detached mode, with the unnecessary services disabled (would disable the ui service too, but the gateway service needs it)
      docker compose -f ./docker-compose.dev.yaml up --detach --scale seed-dev-data=0 --scale ui-gql-codegen=0

      # running the codegen check from a separate container, outside of the docker compose environment, because when I was using the codegen
      # check inside the compose environment (with the --exit-code-from flag set), cloud build was consistently getting 137 exit codes
      # regardless of the outcome of the checks. See: https://github.com/HC-IPPM/safe-inputs/pull/724/commits/36abe66a15020daf70f3ed3e4d3dbd5b3b96fd0b
      docker run \
        --volume "${PWD}":/home/project \
        --workdir /home/project \
        --network host \
        --entrypoint npm \
        node:22-alpine3.21@sha256:6e80991f69cc7722c561e5d14d5e72ab47c0d6b6cfb3ae50fb9cf9a7b30fdf97 \
        run gql-codegen:check

      docker compose -f ./docker-compose.dev.yaml down

  - id: generate-sbom-if-main
    name: 'gcr.io/cloud-builders/docker@sha256:b991d50960b337f581ad77ea2a59259a786d177019aa64d8b3acb01f65dbc154'
    dir: ui
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo $BRANCH_NAME
        if [[ "$BRANCH_NAME" == "main" ]]
        then
          docker run --rm -v /workspace:/workspace anchore/syft:latest /workspace -o cyclonedx-json > /workspace/sbom.json
        else
          exit 0
        fi

  - id: upload-sbom-to-gcs-bucket-if-main
    name: 'gcr.io/cloud-builders/gsutil@sha256:b4dc18198901e93108dba92b8969e73849743c3c061efe13c96764723cecc4b2'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "main" ]]
        then
          gsutil cp /workspace/sbom.json gs://safe-inputs-devsecops-outputs-for-dashboard/SBOM/SBOM-${COMMIT_SHA}.json
        else
          exit 0
        fi

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
