steps:
  - id: 'Install dependencies'
    name: 'node:lts-alpine3.19@sha256:2d8c24d9104bda27e07dced6d7110aa728dd917dde8255d8af3678e532b339d6'
    entrypoint: 'npm'
    dir: ./
    args: ['ci'] # assumes postinstall script in the root level package.json to also install the sub-directory dependencies

  - id: 'Prettier check'
    name: 'node:lts-alpine3.19@sha256:2d8c24d9104bda27e07dced6d7110aa728dd917dde8255d8af3678e532b339d6'
    entrypoint: 'npm'
    dir: ./
    args: ['run', 'prettier']

  - id: 'Eslint check'
    name: 'node:lts-alpine3.19@sha256:2d8c24d9104bda27e07dced6d7110aa728dd917dde8255d8af3678e532b339d6'
    entrypoint: 'npm'
    dir: ./
    args: ['run', 'eslint:ci'] # currently allowing warnings, but could be tightened up post https://github.com/PHACDataHub/safe-inputs/issues/144

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
