apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: safe-inputs
build:
  artifacts:
    - image: northamerica-northeast1-docker.pkg.dev/pdcp-cloud-005-safeinputs/safeinputs/ui
      context: ui
      docker:
        dockerfile: ./ui/Dockerfile
    - image: northamerica-northeast1-docker.pkg.dev/pdcp-cloud-005-safeinputs/safeinputs/api
      context: api
      docker:
        dockerfile: ./api/Dockerfile
portForward:
  - resourceType: service
    resourceName: ui
    namespace: ui
    port: 3000
    localPort: 3000
manifests:
  kustomize:
    paths:
      - ./ui
      - ./api
