steps:
  - id: 'Run tests for a11y scanning'
    name: 'gcr.io/cloud-builders/docker@sha256:084b578fa5287bf10254d0146b813b7175ad4e8aa232d0832b8410a459b4bbcd'
    dir: 'devsecops/axe-testing'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t axe-e2e . && \
        docker run --rm --network host axe-e2e npm run test:all
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
