steps:
  - id: 'Run tests for a11y scanning'
    dir: 'devsecops/axe-testing'
    name: 'gcr.io/cloud-builders/docker@sha256:12a042c896f65aa5bb89dc99470029d293dc8569da1baf77c6ff8d4142b267d4'
    script: |
      #!/usr/bin/env bash
      set -o errexit
      set -o pipefail
      set -o nounset

      # Create the coverage directory 
      mkdir -p /workspace/coverage
      chmod -R 777 /workspace/coverage

      # Run tests in the Docker container with volume mounting for coverage report 
      docker build -t axe-e2e .
      docker run --rm --network host -v /workspace/coverage:/app/coverage axe-e2e npm run test:all

  - id: 'Upload test coverage report to bucket'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest@sha256:e0246385c6f43e997bb49541de7c684846ee9c2baa738a68613f14cab987feb8'
    dir: 'devsecops/axe-testing'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Copy upload script
        cp ../code-coverage-reporting/upload-coverage-to-gcs.sh upload-coverage-to-gcs.sh

        # Upload coverage to GCS
        ./upload-coverage-to-gcs.sh \
          --cloudbuild-dir a11y \
          --coverage-dir /workspace/coverage \
          --branch-name $BRANCH_NAME \
          --short-sha $SHORT_SHA
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
