steps:
  - id: 'Run tests for a11y scanning'
    dir: 'devsecops/axe-testing'
    name: 'gcr.io/cloud-builders/docker@sha256:8a9bff005803926fbc760f9528b708c259ac170b5e93082a9c2342a731945f66'
    script: |
      #!/usr/bin/env bash
      set -o errexit
      set -o pipefail
      set -o nounset

      # Create the coverage directory 
      mkdir -p /workspace/coverage
      chmod -R 777 /workspace/coverage

      # Run tests in the Docker container with volume mounting for coverage report 
      docker build -t axe-e2e .
      docker run --rm --network host -v /workspace/coverage:/app/coverage axe-e2e npm run test:all

  - id: 'Upload test coverage report to bucket'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    dir: 'devsecops/axe-testing'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Copy upload script
        cp ../code-coverage-reporting/upload-coverage-to-gcs.sh upload-coverage-to-gcs.sh

        # Upload coverage to GCS
        ./upload-coverage-to-gcs.sh \
          --cloudbuild-dir a11y \
          --coverage-dir /workspace/coverage \
          --branch-name $BRANCH_NAME \
          --short-sha $SHORT_SHA
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
