steps:
  - id: 'Run tests for a11y scanning'
    name: 'gcr.io/cloud-builders/docker@sha256:4142704d3ab038830d9a0d4ba8c2bbc1b6eef50e3a14b9e00a3066b3ee9d1a03'
    dir: 'devsecops/axe-testing'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t axe-e2e . && \
        docker run --rm --network host axe-e2e npm run test:all
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
