FROM node:lts-alpine3.19@sha256:2d8c24d9104bda27e07dced6d7110aa728dd917dde8255d8af3678e532b339d6

WORKDIR /app

# We don't need the standalone Chromium for puppeteer
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH='/usr/bin/chromium-browser'

# Install packages (Chromium and dependencies)
RUN apk update && apk add --no-cache \
  chromium \
  nss \
  freetype \
  harfbuzz \
  ca-certificates 
  # ttf-freefont # only needed if testing fonts - leaving out for now 

# Copy package files and install dependencies
COPY package*.json ./
RUN npm ci

# Copy the rest of the source code for building
COPY ./axeignore.json .
COPY ./src ./src
COPY ./jest.config.cjs .
COPY ./index.js .
COPY ./tests .

# Install project dependencies
RUN npm install --include=dev 

# Copy the rest of the project files
COPY . .

# Expose the port for the local server
EXPOSE 8080

# Run the test
CMD ["npm", "run", "test:all"]