---
apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mongodb
  namespace: mongodb
spec:
  interval: 24h
  url: https://mongodb.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: mongodb
spec:
  interval: 1m
  chart:
    spec:
      chart: community-operator
      version: "0.10.0"
      sourceRef:
        kind: HelmRepository
        name: mongodb
        namespace: mongodb
      interval: 12h
  values:
    operator:
      watchNamespace: "*"
