apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
  namespace: istio-ingress
spec:
  type: ClusterIP
  selector:
    app: oauth2-proxy
  ports:
    - name: http-oauthproxy
      port: 4180
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
  namespace: istio-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: istio-proxy
          image: auto
          resources:
            requests:
              cpu: 50m
              memory: 112Mi
          securityContext:
            allowPrivilegeEscalation: false
        - name: oauth2-proxy
          image: 'quay.io/oauth2-proxy/oauth2-proxy:v7.7.1@sha256:f6a4aa83a27e316114bf79664302b1ffb2cc8ce697fb479273af4feb3fb16fe3'
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 4180
          args:
            - --provider=google
            - --upstream=static://200
            - --http-address=0.0.0.0:4180
            - --client-id=$(OAUTH_CLIENT_ID)
            - --client-secret=$(OAUTH_CLIENT_SECRET)
            - --cookie-secret=$(OAUTH_COOKIE_SECRET)
            - --email-domain=*
            - --cookie-refresh=1h
            - --cookie-expire=4h
            - --set-xauthrequest
            - --pass-access-token
            - --set-authorization-header
            - --skip-provider-button
            - --reverse-proxy
            - --whitelist-domain=.dev.safeinputs.alpha.phac-aspc.gc.ca
            - --cookie-domain=.dev.safeinputs.alpha.phac-aspc.gc.ca
            - --redirect-url=https://oauth.dev.safeinputs.alpha.phac-aspc.gc.ca/oauth2/callback
          env:
            - name: OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: OAUTH_CLIENT_ID
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: OAUTH_CLIENT_SECRET
            - name: OAUTH_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: OAUTH_COOKIE_SECRET
          resources:
            requests:
              cpu: 200m
              memory: 400Mi
