apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: northamerica-northeast1-docker.pkg.dev/pdcp-cloud-005-safeinputs/safeinputs/api:main-6541877-1716931805 # {"$imagepolicy": "flux-system:api"}
          securityContext:
            # No new privs for process or it's children
            # https://github.com/kubernetes/design-proposals-archive/blob/main/auth/no-new-privs.md
            allowPrivilegeEscalation: false
          env:
            - name: MDB_CONNECT_STRING
              valueFrom:
              secretKeyRef:
                name: mongodb-api-user-connect-string
                key: connectionString.standardSrv
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: auth-js-secret
            - name: GCNotifyApiKey
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: gcnotify_api_key
            - name: GCNotifyTemplateID
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: gcnotify_template_id
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
        - name: istio-proxy
          image: auto
          resources:
            requests:
              cpu: 100m
              memory: 112Mi
          securityContext:
            allowPrivilegeEscalation: false
status: {}
