# The mongodb operator generates user credentials from this secret. Once the credentials are generated,
# this secret is no longer required. Retain it for reference/redeployment
# https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/users.md
apiVersion: v1
kind: Secret
metadata:
    name: mongodb-app-user-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:E11oFVBBha1/SKl1atpxd1RwjHEmhQaQPUPRLvwZT+SkOqDIKKYu/JlLPG26JA==,iv:daeZFRGGnwLDMKprZQn+UKjc8OYNaRMvBNqajHyQD4I=,tag:OO2Ya35SRC8KTnfh+OseOA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/pdcp-cloud-005-safeinputs/locations/northamerica-northeast1/keyRings/sops/cryptoKeys/sops-key
          created_at: "2024-05-28T19:53:51Z"
          enc: CiQAaB3bGJDuorKN0XnyQioxyZZOcyPUi2kkmQS6bISqB7HLVL8SSQD5W3amM482ddK6m8tdNXJ5j4yQLSiTLl4zTm/xS7NbuZu+dV1w0Io84FZC2UGQwYHdDSlXaXd3vJ84VjJcnF+O4UcLo90xTkw=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-28T19:53:51Z"
    mac: ENC[AES256_GCM,data:f63izkeRQohEbCaCogCo9MQQtsbnz+ySoVEJOqeCSkgrZDECToPiQs25d3SR3urd8t1sfoio9Rttu86CouIrDG8wUsGQhDiK8bnObzQKw04Qw7WkKI6XbXrJLp5JuWgz8sHM3tYVnSRo2bamvmmkB+H+pswjmnvUIdI4lBDk0Lw=,iv:fMagcaDi6t3egqa1nSWLYAEdGpZlyINdRiIb9ThvKs4=,tag:04StmFbFSNn7wbtnRDdzDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
