apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: '6.0.5'
  security:
    authentication:
      modes: ['SCRAM']
  users:
    - name: admin
      db: admin # auth db
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongodb-admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: mongodb-admin-scram
    - name: app
      db: admin # auth db, TODO do we want the app user's auth to live in the app DB? Consider best practices but also possible quirks of k8s mongo management
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongodb-app-user-password
      roles:
        - name: readWrite
          db: api_db # created manually for now, automated DB initialization TODO
      scramCredentialsSecretName: mongodb-app-user-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

  statefulSet:
    spec:
      # Set persistent disk resources
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ['ReadWriteOnce']
            resources:
              requests:
                storage: 5Gi
        - metadata:
            name: logs-volume
          spec:
            accessModes: ['ReadWriteOnce']
            resources:
              requests:
                storage: 5Gi

      # Set container resources
      template:
        spec:
          containers:
            - name: mongod
              resources:
                requests:
                  cpu: 300m
                  memory: 300Mi
              securityContext:
                allowPrivilegeEscalation: false
            - name: mongodb-agent
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
              securityContext:
                allowPrivilegeEscalation: false
            - name: istio-proxy
              image: auto
              resources:
                requests:
                  cpu: 100m
                  memory: 112Mi
              securityContext:
                allowPrivilegeEscalation: false
          initContainers:
            - name: mongodb-agent-readinessprobe
              resources:
                requests:
                  cpu: 200m
                  memory: 200Mi
