apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api

resources:
  - namespace.yaml
  - operator
  - mongodb-admin-password.enc.yaml
  - mongodb.yaml

patches:
  - target:
      kind: Deployment
      name: mongodb-kubernetes-operator
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: mongodb-kubernetes-operator
      spec:
        template:
          spec:
            containers:
              - name: mongodb-kubernetes-operator
                resources:
                  requests:
                    cpu: 300m
                    memory: 200Mi
                securityContext:
                  allowPrivilegeEscalation: false
              - name: istio-proxy
                image: auto
                resources:
                  requests:
                    cpu: 100m
                    memory: 112Mi
                securityContext:
                  allowPrivilegeEscalation: false
