title: |md

   **Page Layout (`excelParser.tsx`)**

| { near: top-center }


ExcelParsingPage: {
    handleFileUpload
    handleServiceWorkerMessage: {
        setDisplayComponent
        setParserData
    }
    ExcelUploadForm: {
        Props: {
            onSubmit
        }
        Props.style.3d: true
    }
    TableOutput: {
        Props: {
            parserData
            shouldDisplayComponent
        }
        Props.style.3d: true
    }
}

ExcelParsingPage.handleFileUpload <- ExcelParsingPage.ExcelUploadForm.Props.onSubmit

serviceWorker\.ts: {
  messageEventListener: {
    xlsx\.read(workbook file)
    xlsx\.sheet_to_json(sheets)
    postMessage(workbook json)
  }
}

ExcelParsingPage.handleFileUpload -> serviceWorker\.ts.messageEventListener.xlsx\.read(workbook file): workbook file
serviceWorker\.ts.messageEventListener.postMessage(workbook json) -> ExcelParsingPage.handleServiceWorkerMessage: processed workbook file

ExcelParsingPage.handleServiceWorkerMessage.setDisplayComponent -> ExcelParsingPage.TableOutput.Props.displayComponent
ExcelParsingPage.handleServiceWorkerMessage.setParserData -> ExcelParsingPage.TableOutput.Props.parserData