apiVersion: v1
kind: ServiceAccount
metadata:
  name: ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  strategy: {}
  template:
    metadata:
      labels:
        app: ui
    spec:
      serviceAccountName: ui
      # Pod wide security settings:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        # seems to succeed only when specific uid/guid is set
        runAsNonRoot: true
      containers:
        - name: ui
          image: northamerica-northeast1-docker.pkg.dev/phx-01j1tbke0ax/phx-01j1tbke0ax-safeinputs/ui:main-ae24811ef7a0b7a2c9b532a2876233ec3a7e0ddb-1729695557 # {"$imagepolicy": "flux-system:ui"}
          # Container specific security settings:
          securityContext:
            # No new privs for process or it's children
            # https://github.com/kubernetes/design-proposals-archive/blob/main/auth/no-new-privs.md
            allowPrivilegeEscalation: false
            # TODO: npm checks for updates and writes a file
            # Explore disabling check or removing npm
            # readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 200m
              memory: 400Mi
status: {}
