apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-ingress
spec:
  commonName: safeinputs.alpha.phac-aspc.gc.ca
  dnsNames:
    - safeinputs.alpha.phac-aspc.gc.ca
    - entreessecurisees.alpha.phac-aspc.gc.ca
  issuerRef:
    kind: Issuer
    # name: letsencrypt-staging
    name: letsencrypt
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  secretName: tlskeys
status: {}
