env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - https://8080-cs-281831690367-default.cs-us-east1-pkhd.cloudshell.dev/
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: https://8080-cs-281831690367-default.cs-us-east1-pkhd.cloudshell.dev/
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules: []
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: testreport.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: report_json
    reportTitle: ZAP Scanning Report
    template: traditional-json
  type: report
