apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds.yaml
  - sync-config.yaml
  - deployment-config.yaml

patches:
  # Reduced pod resources
  - target:
      kind: Deployment
      name: '(kustomize-controller|source-controller|image-reflector-controller|image-automation-controller|notification-controller)'
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            containers:
              - name: manager
                resources:
                  requests:
                    cpu: 100m
                    memory: 200Mi

  # patch kustomize-controller service account to access GCP KMS for decrypting secrets
  # See https://fluxcd.io/flux/guides/mozilla-sops/#google-cloud
  - patch: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: kustomize-controller
        namespace: flux-system
        annotations:
          iam.gke.io/gcp-service-account: sops-kms@pdcp-cloud-005-safeinputs.iam.gserviceaccount.com
    target:
      kind: ServiceAccount
      name: kustomize-controller
