env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - https://safeinputs.alpha.phac-aspc.gc.ca/
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: https://safeinputs.alpha.phac-aspc.gc.ca/
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules: []
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: zap-reports/testreport.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: zap-reports/report_json
    reportTitle: ZAP Scanning Report
    template: traditional-json
  type: report
