steps:
  - id: deploy-cloud-function-if-main
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: vuln-scanning-artifact-registry
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "main" ]]
        then
          gcloud functions deploy image-vuln-cf-trigger \
              --source /workspace/cloud-function \
              --runtime python39 \
              --trigger-topic container-analysis-occurrences-v1 \
              --entry-point image_vuln_pubsub_handler \
              --allow-unauthenticated \
              --region northamerica-northeast1
        else
          exit 0
        fi

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
