steps:
  - id: 'Run tests for a11y scanning'
    name: 'gcr.io/cloud-builders/docker@sha256:c0987008cb5e77741dc616177ba48cb27a7458f3f62161c82b6c6d5fa4ae8ab5'
    dir: 'devsecops/axe-testing'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t axe-e2e . && \
        docker run --rm --network host axe-e2e npm run test:all
