steps:
  - id: 'Run tests for a11y scanning'
    name: 'gcr.io/cloud-builders/docker@sha256:bc4474abd83f646afd7a324e9224add7c590da318ce60d5752a46867c72e5a0b'
    dir: 'devsecops/axe-testing'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t axe-e2e . && \
        docker run --rm --network host axe-e2e npm run test:all
