apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api

resources:
  - ../../base/api
  - namespace.yaml
  - mongodb-secrets.enc.yaml
  - api-secrets.enc.yaml
  - virtual-service.yaml
  - authzpol.yaml

patches:
  - path: ./deployment-patch.yaml
    target:
      kind: Deployment
      name: api

  - path: ./mongodb-patch.yaml
    target:
      kind: MongoDBCommunity
      name: mongodb
