# The mongodb operator generates user credentials from this secret. Once the credentials are generated,
# this secret is no longer required. Retain it for reference/redeployment
# https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/users.md
apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secrets
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:K9tqxttmmbYtO6HZt6H3dqTXVXpUYKNas6aBq5PKRGQ8Zp+FIaYGOY2Q7Hukiw==,iv:OOoeRwmc/qEhiHNKST3gslY/DvIzSHpdoS3w5VsUqIY=,tag:MJEpuQ/0ayvd9tqkXpVxqw==,type:str]
    api-user-password: ENC[AES256_GCM,data:nMBD/uitFb9HhvDfp1GRa14MPRI8YI64Ty+Vs+npdmnHyGt54mzWr6Ow6ayKXw==,iv:FdTC79+O5f38flJC+KI6e1BpF8EPoW+m2tLo1yKSp/8=,tag:AF8Zx5BqBguRcRPvCGcXqA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/phx-01j1tbke0ax/locations/northamerica-northeast1/keyRings/phx-01j1tbke0ax-sops/cryptoKeys/phx-01j1tbke0ax-sops-flux-key
          created_at: "2024-07-11T19:57:41Z"
          enc: CiQAWQXQWCs/uRkf1vHKBOS7MjHsanSSOEu5BNqF7lQy+IKdHOASSQCvJtFZ8823xY1vWHTc3S5Gb6cxVpP2OhBW+XaMXG2IOj4QXvjqiFPdauna95ukiF7xvMUB7JCAxOnqkr+u6Dt4mGKxHWjWF3I=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-11T19:57:41Z"
    mac: ENC[AES256_GCM,data:OIZMQvwNS7jPjFjBxMGDF2uX+dj8bQ2mYKkLQHLkZJ5M2Ix5WLupMA0GXudZBq64ABuggfS9RRndNvUX3f7ZwwYuHIDlsU4tIlYMqh95YUsKHj7SXHEbprTTciTiIQUXHtQPYPxH4PcUimhW4LjhfvKxuTojDoxZSSefnXoXgNE=,iv:sXwdlqGozsFfVeljNQqdmEXYnEK7Cd9CU2umhy6Kq5M=,tag:j/HEnvaA2OFXaze+4+wndg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
