apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# clusterwide (default namespace) role creation and bindings
resources:
  - clusterwide
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# operator name-spaced resources, configured to manage a mongo resource in the api namespace
namespace: mongodb-operator
resources:
  - crd
  - rbac
  - manager
# See notes on deploying the mongodb operator in a different namespace than the mongodb resources it manages
# https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md#install-in-a-different-namespace-using-kubectl
patches:
  - target:
      kind: Deployment
      name: mongodb-kubernetes-operator
    # patching for a) resources and b) to set the operator's WATCH_NAMESPACE env var to the namespace(s) where mongo resources are deploying
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: mongodb-kubernetes-operator
      spec:
        template:
          spec:
            containers:
              - name: mongodb-kubernetes-operator
                resources:
                  requests:
                    cpu: 300m
                    memory: 200Mi
                securityContext:
                  allowPrivilegeEscalation: false
                env:
                  - name: WATCH_NAMESPACE
                    value: api
              - name: istio-proxy
                image: auto
                resources:
                  requests:
                    cpu: 100m
                    memory: 112Mi
                securityContext:
                  allowPrivilegeEscalation: false
  - target:
      kind: ClusterRoleBinding
      name: mongodb-kubernetes-operator
    # when deploying operator and resource in different namespaces, need to patch the ClusterRoleBinding to specify _the operator's_ namespace
    patch: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: mongodb-kubernetes-operator
      subjects:
      - kind: ServiceAccount
        namespace: mongodb-operator
        name: mongodb-kubernetes-operator
