steps:
  - id: 'Install dependencies'
    name: 'node:lts-alpine3.19@sha256:40dc4b415c17b85bea9be05314b4a753f45a4e1716bb31c01182e6c53d51a654'
    dir: ui
    entrypoint: npm
    args: ['ci', '--no-optional']

  - id: 'Check types'
    name: 'node:lts-alpine3.19@sha256:40dc4b415c17b85bea9be05314b4a753f45a4e1716bb31c01182e6c53d51a654'
    dir: ui
    entrypoint: npm
    args: ['run', 'typecheck']

  - id: Test
    name: 'node:lts-alpine3.19@sha256:40dc4b415c17b85bea9be05314b4a753f45a4e1716bb31c01182e6c53d51a654'
    dir: ui
    entrypoint: npm
    args: ['test']

  - id: 'Axe a11y testing setup'
    name: 'gcr.io/cloud-builders/docker@sha256:371be7d6ff284257c33a159859d46495cec495e050766a4f087425247f12a132'
    dir: ./
    script: |
      #!/bin/bash
      set -o errexit
      set -o pipefail
      set -o nounset

      # docker compose dev environment, detached mode, with ui-gql-codegen disabled because it a) doesn't need to run here, and
      # b) has permissions issues when running in this context
      docker compose -f ./docker-compose.dev.yaml up -d --scale ui-gql-codegen=0

      docker build -t axe ./devsecops/axe-testing

      # fix for a permission issues when running the axe tests, need to be able to write to ./axe-results/*.json
      mkdir -p /workspace/axe-results
      chmod -R 777 /workspace/axe-results

      # make sure the ui server is ready before continuing
      docker run \
        --volume "${PWD}":/home/project \
        --workdir /home/project \
        --network host \
        --entrypoint node \
        node:lts-alpine3.19@sha256:2d8c24d9104bda27e07dced6d7110aa728dd917dde8255d8af3678e532b339d6 \
        ./wait_for_service.cjs http://localhost:8080/signin

  - id: 'Axe a11y testing'
    name: 'gcr.io/cloud-builders/docker@sha256:371be7d6ff284257c33a159859d46495cec495e050766a4f087425247f12a132'
    args: [
        'run',
        '--network',
        'host', # to access the dev environment
        '--rm',
        '--volume',
        '/workspace/axe-results:/app/axe-results',
        '--env',
        '${COMMIT_SHA}',
        'axe',
      ]

  - id: upload-axe-results-gcs
    name: 'gcr.io/cloud-builders/gsutil@sha256:1d6b8cdc591206a13033477fa9df0b0fe6a282b5f01a80082d0f5969d40d24b0'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp /workspace/axe-results/ci_axe_results_*.json \
        gs://safe-inputs-devsecops-outputs-for-dashboard/axe-ci-results/$BRANCH_NAME-$COMMIT_SHA.json

  - id: docker-compose-down-dev-environment
    name: 'gcr.io/cloud-builders/docker@sha256:371be7d6ff284257c33a159859d46495cec495e050766a4f087425247f12a132'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker compose -f ./docker-compose.dev.yaml down -v

  - id: generate-image-name
    name: 'gcr.io/cloud-builders/docker@sha256:371be7d6ff284257c33a159859d46495cec495e050766a4f087425247f12a132'
    entrypoint: 'bash'
    dir: ui
    args:
      - '-c'
      - |
        echo "northamerica-northeast1-docker.pkg.dev/${PROJECT_ID}/phx-01j1tbke0ax-safeinputs/ui:$BRANCH_NAME-$COMMIT_SHA-$(date +%s)" > /workspace/imagename

  - id: build-if-main
    name: 'gcr.io/cloud-builders/docker@sha256:371be7d6ff284257c33a159859d46495cec495e050766a4f087425247f12a132'
    entrypoint: 'bash'
    dir: ui
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "main" ]]
        then
          image=$(cat /workspace/imagename)
          docker build -t $image -f ./Dockerfile.prod .
        else
          exit 0
        fi

  - id: push-if-main
    name: 'gcr.io/cloud-builders/docker@sha256:371be7d6ff284257c33a159859d46495cec495e050766a4f087425247f12a132'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "main" ]]
        then
          image=$(cat /workspace/imagename)
          docker push $image
        else
          exit 0
        fi
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
