steps:
  - name: node:20-alpine@sha256:df01469346db2bf1cfc1f7261aeab86b2960efa840fe2bd46d83ff339f463665
    id: install
    dir: ui
    entrypoint: npm
    args: ['ci', '--no-optional']

  - name: node:20-alpine@sha256:df01469346db2bf1cfc1f7261aeab86b2960efa840fe2bd46d83ff339f463665
    id: test
    dir: ui
    entrypoint: npm
    args: ['test']

  - name: 'gcr.io/cloud-builders/docker@sha256:4407a8c124991edc4c1a63a3c9e2ea512766e7a6d1476bcb7eabc719003fdb7c'
    id: generate-image-name
    entrypoint: 'bash'
    dir: ui
    args:
      - '-c'
      - |
        echo "northamerica-northeast1-docker.pkg.dev/${PROJECT_ID}/safeinputs/ui:$BRANCH_NAME-$SHORT_SHA-$(date +%s)" > /workspace/imagename

  - name: 'gcr.io/cloud-builders/docker@sha256:4407a8c124991edc4c1a63a3c9e2ea512766e7a6d1476bcb7eabc719003fdb7c'
    id: build-if-main
    entrypoint: 'bash'
    dir: ui
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "main" ]]
        then
          image=$(cat /workspace/imagename)
          docker build -t $image -f ./Dockerfile.prod .
        else
          exit 0
        fi

  - name: 'gcr.io/cloud-builders/docker@sha256:4407a8c124991edc4c1a63a3c9e2ea512766e7a6d1476bcb7eabc719003fdb7c'
    id: push-if-main
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "main" ]]
        then
          image=$(cat /workspace/imagename)
          docker push $image
        else
          exit 0
        fi
