FROM node:18.6.0-alpine3.15 AS builder

RUN mkdir -p /home/ui
# Copy only package.json over to avoid running the `npm install`
# stanza after every source code change.
COPY package.json /home/ui
# Set /home/ui as cwd.
WORKDIR /home/ui
RUN npm i
# Need rwx permissions on node_modules cache to resolve issue with
# .eslintcache being moved to node_modules/.cache in newer
# versions of React (see https://stackoverflow.com/a/67540612).
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

# Copy source code to /home/ui after npm install step
COPY . /home/ui

# Need to allow rwx over `src/` to enable skaffold's file sync
# feature to work correctly (see
# https://stackoverflow.com/a/57740146 for related issue).
RUN chmod -R 777 src/

# Start container as non-root user.
USER node
EXPOSE 3000
# Run the development server 
ENTRYPOINT ["npm", "run", "start"]

