apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mesh-gateway-cert
  namespace: istio-ingress
spec:
  # this will be patched within ../../clusters/gke/components.yaml
  dnsNames: []
  issuerRef:
    kind: ClusterIssuer
    name: issuer
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  secretName: tlskeys
