steps:
  - id: deploy-cloud-function-if-main
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: devsecops/artifact-registry-vulnerability-scanning/
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$_BRANCH_NAME" == "main" ]]
        then
          gcloud functions deploy imageVulnPubSubHandler \
            --gen2 \
            --source=./cloud-function \
            --runtime=nodejs18 \
            --trigger-topic=container-analysis-occurrences-v1 \
            --entry-point=imageVulnPubSubHandler \
            --set-env-vars=BUCKET_NAME=$_BUCKET_NAME \
            --region=northamerica-northeast1 \
            --service-account $_VULN_CLOUD_FUNCTION_SERVICE_ACCOUNT@$_PROJECT_ID.iam.gserviceaccount.com
        else
          exit 0
        fi

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
