steps:
  # - id: test
  #   name: 'node:lts-alpine3.19@sha256:da778fcbffb7c3a83f1649d029a53b5f21ac6635ac24cf1b7fa7c2956d5509ed'
  #   dir: devsecops/artifact-registry-vulnerability-scanning/cloud-function
  #   entrypoint: npm
  #   args: ['test']

  - id: deploy-cloud-function-if-main
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: devsecops/artifact-registry-vulnerability-scanning/
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "main" ]]
        then
          gcloud functions deploy imageVulnPubSubHandler \
              --source ./cloud-function \
              --runtime nodejs18 \
              --trigger-topic container-analysis-occurrences-v1 \
              --entry-point imageVulnPubSubHandler \
              --set-env-vars BUCKET_NAME=$BUCKET_NAME \
              --region=$REGION
        else
          exit 0
        fi

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
