steps:
  - id: deploy-cloud-function-if-main
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:3de00d1ff412222f53cf71e7e20c99c13ec3e8e21dc3056e2d6cedc9408afaee'
    dir: devsecops/artifact-registry-vulnerability-scanning/
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${BRANCH_NAME}" == "main" ]]
        then
          gcloud functions deploy imageVulnPubSubHandler \
            --gen2 \
            --source=./cloud-function \
            --runtime=nodejs18 \
            --trigger-topic=container-analysis-occurrences-v1 \
            --entry-point=imageVulnPubSubHandler \
            --set-env-vars=BUCKET_NAME=${_BUCKET_NAME} \
            --region=northamerica-northeast1 \
            --build-service-account=projects/${PROJECT_ID}/serviceAccounts/${_CLOUDBUILD_SERVICE_ACCOUNT} \
            --service-account=${_VULN_CLOUD_FUNCTION_SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com
        else
          exit 0
        fi

substitutions:
  _BUCKET_NAME: safe-inputs-devsecops-outputs-for-dashboard
  _VULN_CLOUD_FUNCTION_SERVICE_ACCOUNT: phx-01j1tbke0ax-vuln-gcf
  _CLOUDBUILD_SERVICE_ACCOUNT: phx-01j1tbke0ax-cloudbuild@phx-01j1tbke0ax.iam.gserviceaccount.com

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
