steps:
  - id: deploy-cloud-function-if-main
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:3a24ff5f089d9ce3627306873ef1e1061488a63ae12c0bd0b5c24ec5ee594798'
    dir: devsecops/artifact-registry-vulnerability-scanning
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" = "main" ]]; then
          gcloud functions deploy imageVulnPubSubHandler \
            --gen2 \
            --source=./cloud-function \
            --runtime=nodejs18 \
            --trigger-topic=container-analysis-occurrences-v1 \
            --entry-point=imageVulnPubSubHandler \
            --set-env-vars=BUCKET_NAME=${_BUCKET_NAME} \
            --region=northamerica-northeast1 \
            --build-service-account=projects/phx-01j1tbke0ax/serviceAccounts/phx-01j1tbke0ax-vgcf-build@phx-01j1tbke0ax.iam.gserviceaccount.com \
            --service-account=phx-01j1tbke0ax-vgcf-runtime@phx-01j1tbke0ax.iam.gserviceaccount.com \
            --docker-repository=northamerica-northeast1-docker.pkg.dev/phx-01j1tbke0ax/phx-01j1tbke0ax-vuln-cloudfunction
        else
          exit 0
        fi

  - id: get-and-save-artifact-registry-image-digest-if-main
    # This is a workaround to help filter only current image vulnerabilities for dashboard - we need the AR image digest for this.
    # No tags, unfortunately with this one, it's autocreated with the deployment, so first sorting to get most recent.
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest@sha256:3a24ff5f089d9ce3627306873ef1e1061488a63ae12c0bd0b5c24ec5ee594798'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${BRANCH_NAME}" == "main" ]]
        then
        short_digest="$(gcloud artifacts files list \
          --project=phx-01j1tbke0ax \
          --repository=phx-01j1tbke0ax-vuln-cloudfunction \
          --location=northamerica-northeast1 \
          --package=phx--01j1tbke0ax__northamerica--northeast1__image_vuln_pub_sub_handler \
          --sort-by=~CREATE_TIME)"

        short_sha="$(echo "${short_digest}" | awk -F'sha256:' 'NR==1 {print substr($2, 1, 12)}')"
        echo "${short_sha}" | gsutil cp - "gs://safe-inputs-devsecops-outputs-for-dashboard/COMMIT_SHAs/gcf-vuln__${short_sha}.txt"

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
