steps:
  - id: deploy-cloud-function-if-main
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:3de00d1ff412222f53cf71e7e20c99c13ec3e8e21dc3056e2d6cedc9408afaee'
    dir: devsecops/artifact-registry-vulnerability-scanning/
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy imageVulnPubSubHandler \
          --gen2 \
          --source=./cloud-function \
          --runtime=nodejs18 \
          --trigger-topic=container-analysis-occurrences-v1 \
          --entry-point=imageVulnPubSubHandler \
          --set-env-vars=BUCKET_NAME=${_BUCKET_NAME} \
          --region=northamerica-northeast1 \
          --build-service-account=projects/phx-01j1tbke0ax/serviceAccounts/phx-01j1tbke0ax-cloudbuild@phx-01j1tbke0ax.iam.gserviceaccount.com \
          --service-account=phx-01j1tbke0ax-vuln-gcf@phx-01j1tbke0ax.iam.gserviceaccount.com \
          --docker-repository=northamerica-northeast1-docker.pkg.dev/phx-01j1tbke0ax/phx-01j1tbke0ax-vuln-cloudfunction

substitutions:
  _BUCKET_NAME: safe-inputs-devsecops-outputs-for-dashboard

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
