steps:
  - id: 'Check types'
    name: 'node:lts-alpine3.19@sha256:97f02cbb1c8ef6eefcfb1b1f958c012362758972cf125a99c09bd18b26a716c9'
    entrypoint: 'sh'
    dir: api
    args:
      - '-c'
      - |
        npm ci && npm run typecheck

  - id: 'Run tests'
    name: 'gcr.io/cloud-builders/docker@sha256:098a87640ad3ccb27308d5f006d6898c6078a9dcb8433b7b0101932671e05b60'
    script: |
      #!/usr/bin/env bash
      set -o errexit
      set -o pipefail
      set -o nounset

      # disable TTY output for the compose environment, the ansi characters printed when a TTY is attached
      # are just junk characters to the GCP cloudbuild logs
      DOCKER_NETWORK=cloudbuild DOCKER_TTY=false docker compose -f api/docker-compose.dev-test.yaml up --exit-code-from api-test

  - name: 'gcr.io/cloud-builders/docker@sha256:098a87640ad3ccb27308d5f006d6898c6078a9dcb8433b7b0101932671e05b60'
    id: generate-image-name
    entrypoint: 'bash'
    dir: api
    args:
      - '-c'
      - |
        echo "northamerica-northeast1-docker.pkg.dev/${PROJECT_ID}/phx-01j1tbke0ax-safeinputs/api:$BRANCH_NAME-$SHORT_SHA-$(date +%s)" > /workspace/imagename

  - name: 'gcr.io/cloud-builders/docker@sha256:098a87640ad3ccb27308d5f006d6898c6078a9dcb8433b7b0101932671e05b60'
    id: build-if-main
    entrypoint: 'bash'
    dir: api
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "main" ]]
        then
          image=$(cat /workspace/imagename)
          docker build -t $image -f ./Dockerfile.prod .
        else
          exit 0
        fi

  - name: 'gcr.io/cloud-builders/docker@sha256:098a87640ad3ccb27308d5f006d6898c6078a9dcb8433b7b0101932671e05b60'
    id: push-if-main
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "main" ]]
        then
          image=$(cat /workspace/imagename)
          docker push $image
        else
          exit 0
        fi
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
