steps:
  - id: 'Check types'
    name: 'node:lts-alpine3.19@sha256:1bdec9c67503d33348be6e73a8e5e94aad679b32da15e4fd3956e5e48f87f623'
    entrypoint: 'sh'
    dir: api
    args:
      - '-c'
      - |
        npm ci && npm run typecheck

  - id: 'Run tests'
    name: 'gcr.io/cloud-builders/docker@sha256:df8266d59a8dc5e036ca07580066becd061619ea7f1dd8a51806468276d036b9'
    script: |
      #!/usr/bin/env bash
      set -o errexit
      set -o pipefail
      set -o nounset

      # disable TTY output for the compose environment, the ansi characters printed when a TTY is attached
      # are just junk characters to the GCP cloudbuild logs
      DOCKER_NETWORK=cloudbuild DOCKER_TTY=false docker compose -f api/docker-compose.dev-test.yaml up --exit-code-from api-test

  - name: 'gcr.io/cloud-builders/docker@sha256:df8266d59a8dc5e036ca07580066becd061619ea7f1dd8a51806468276d036b9'
    id: generate-image-name
    entrypoint: 'bash'
    dir: api
    args:
      - '-c'
      - |
        echo "northamerica-northeast1-docker.pkg.dev/${PROJECT_ID}/safeinputs/api:$BRANCH_NAME-$SHORT_SHA-$(date +%s)" > /workspace/imagename

  - name: 'gcr.io/cloud-builders/docker@sha256:df8266d59a8dc5e036ca07580066becd061619ea7f1dd8a51806468276d036b9'
    id: build-if-main
    entrypoint: 'bash'
    dir: api
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "main" ]]
        then
          image=$(cat /workspace/imagename)
          docker build -t $image -f ./Dockerfile.prod .
        else
          exit 0
        fi

  - name: 'gcr.io/cloud-builders/docker@sha256:df8266d59a8dc5e036ca07580066becd061619ea7f1dd8a51806468276d036b9'
    id: push-if-main
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "main" ]]
        then
          image=$(cat /workspace/imagename)
          docker push $image
        else
          exit 0
        fi
