FROM node:lts-alpine3.19@sha256:97f02cbb1c8ef6eefcfb1b1f958c012362758972cf125a99c09bd18b26a716c9

ENV NODE_ENV production

WORKDIR /app

COPY . .
RUN npm ci

USER node

CMD npm --no-update-notifier start
