FROM node:lts-alpine3.19@sha256:da778fcbffb7c3a83f1649d029a53b5f21ac6635ac24cf1b7fa7c2956d5509ed

ENV NODE_ENV production

WORKDIR /app

COPY . .
RUN npm ci

USER node

CMD npm --no-update-notifier start
