FROM node:lts-alpine3.19@sha256:2d8c24d9104bda27e07dced6d7110aa728dd917dde8255d8af3678e532b339d6

ENV NODE_ENV production

WORKDIR /app

COPY . .
RUN npm ci

USER node

CMD npm --no-update-notifier start
