apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/ui
  - namespace.yaml
  - virtual-service.yaml
  - authzpol.yaml

namespace: ui

patches:
  - path: ./deployment-patch.yaml
    target:
      kind: Deployment
      name: ui
